USE Master					
	GO					
	IF  EXISTS (SELECT * FROM SYSdatabases  WHERE Name = N'POLYPRO')					
	Drop Database POLYPRO				
	Go	

--------------------
create database POLYPRO
go
use POLYPRO
go
	IF  EXISTS (SELECT * FROM SYSOBJECTS  WHERE Name = N'CHUYENDE')					
	Drop table CHUYENDE					
	Go
	CREATE TABLE CHUYENDE(
	MACHUYENDE nvarchar(50) NOT NULL,
	TENCHUYENDE nvarchar(50) NULL,
	HOCPHI float not NULL DEFAULT 0,
	THOILUONG int not NULL DEFAULT 30,
	MOTA nvarchar(255) not NULL,
	HINH nvarchar(max) not null
	CONSTRAINT PK_CHUYENDE PRIMARY KEY (MACHUYENDE),
	CHECK(HOCPHI >= 0 AND THOILUONG > 0)
	)
	IF  EXISTS (SELECT * FROM SYSOBJECTS  WHERE Name = N'NHANVIEN')					
	Drop table NHANVIEN					
	Go	

	CREATE TABLE NHANVIEN(
	MANHANVIEN nvarchar(50) NOT NULL,
	MATKHAU nvarchar(50) not NULL,
	HOTEN nvarchar(50) not NULL,
	VAITRO bit not NULL DEFAULT 0,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANHANVIEN)
	)

	insert into NHANVIEN(MANHANVIEN,MATKHAU,HOTEN,VAITRO) values (N'admin',N'admin',N'Admin',1)
	
	IF  EXISTS (SELECT * FROM SYSOBJECTS  WHERE Name = N'NGUOIHOC')					
	Drop table NGUOIHOC					
	Go
	CREATE TABLE NGUOIHOC(
	MANGUOIHOC nchar(7) NOT NULL,
	HOTEN nvarchar(50) not NULL,
	NGAYSINH date not NULL,
	GIOITINH bit not NULL DEFAULT 0,
	DIENTHOAI nvarchar(50) not NULL,
	EMAIL nvarchar(50) not NULL,
	GHICHU nvarchar(max)  NULL,
	MANHANVIEN nvarchar(50) NOT NULL,
	NGAYDANGKI date default getdate(),
	CONSTRAINT PK_NGUOIHOC PRIMARY KEY (MANGUOIHOC),
	CONSTRAINT FK_NGUOIHOC_NHANVIEN FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN
	)
	
	IF  EXISTS (SELECT * FROM SYSOBJECTS  WHERE Name = N'KHOAHOC')					
	Drop table KHOAHOC					
	Go
	CREATE TABLE KHOAHOC(
	MAKHOAHOC int identity NOT NULL,
	MACHUYENDE nvarchar(50) NOT NULL,
	HOCPHI float not NULL DEFAULT 0,
	THOILUONG int not NULL DEFAULT 0,
	NGAYKHAIGIANG date not NULL,
	GHICHU nvarchar(50) not NULL,
	MANHANVIEN nvarchar(50) NOT NULL,
	NGAYTAO date not null,
	CHECK(HocPhi >= 0 AND ThoiLuong > 0),
	CONSTRAINT PK_KHOAHOC PRIMARY KEY (MAKHOAHOC),
	CONSTRAINT FK_KHOAHOC_NHANVIEN FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN,
	CONSTRAINT FK_KHOAHOC_CHUYENDE FOREIGN KEY(MACHUYENDE) REFERENCES CHUYENDE,
	)
	IF  EXISTS (SELECT * FROM SYSOBJECTS  WHERE Name = N'HOCVIEN')					
	Drop table HOCVIEN					
	Go
	CREATE TABLE HOCVIEN(
	MAHOCVIEN int identity NOT NULL,
	MAKHOAHOC int  NOT NULL,
	MANGUOIHOC nchar(7) NOT NULL,
	DIEMTRUNGBINH float not NULL,
	CONSTRAINT PK_HOCVIEN PRIMARY KEY (MAHOCVIEN),
	CONSTRAINT FK_HOCVIEN_NGUOIHOC FOREIGN KEY(MANGUOIHOC) REFERENCES NGUOIHOC,
	CONSTRAINT FK_HOCVIEN_KHOAHOC FOREIGN KEY(MAKHOAHOC) REFERENCES KHOAHOC
	)







	---thủ tục thống kê điểm
	if OBJECT_ID('sp_BangDiem') is not null
drop proc spHD
go
	CREATE PROC sp_BangDiem
	@MaKH INT 
AS BEGIN  
	SELECT   
		nh.MANGUOIHOC,   
		nh.HOTEN,   
		hv.DIEMTRUNGBINH 
	FROM HocVien hv JOIN NguoiHoc nh ON nh.MANGUOIHOC=hv.MANGUOIHOC  
	WHERE hv.MAKHOAHOC = @MaKH  
	ORDER BY hv.DIEMTRUNGBINH DESC 
END 
GO

if OBJECT_ID('sp_ThongKeDiem') is not null
drop proc spThongKeDiem
go
CREATE PROC sp_ThongKeDiem 
AS BEGIN  
	SELECT   
		TENCHUYENDE CHUYENDE,   
		COUNT(MAHOCVIEN) SoHV,     
		MAX(DIEMTRUNGBINH) CaoNhat, 
		MIN(DIEMTRUNGBINH) ThapNhat,  
		ROUND(AVG(DIEMTRUNGBINH),1) TrungBinh
	FROM KhoaHoc kh   JOIN HocVien hv ON kh.MAKHOAHOC=hv.MAKHOAHOC JOIN CHUYENDE cd ON cd.MACHUYENDE=kh.MACHUYENDE  
	GROUP BY TENCHUYENDE
END
GO
-----thủ tục thống kê doanh thu
if OBJECT_ID('sp_ThongKeDoanhThu') is not null
drop proc sp_ThongKeDoanhThu
go
CREATE PROC sp_ThongKeDoanhThu 
@Year int
AS BEGIN  
	SELECT   
		TENCHUYENDE CHUYENDE,   
		COUNT(DISTINCT kh.MAKHOAHOC) SoKH,   
		COUNT(hv.MAHOCVIEN) SoHV,   
		SUM(kh.HOCPHI) DoanhThu,   
		MIN(kh.HOCPHI) ThapNhat,   
		MAX(kh.HOCPHI) CaoNhat,   
		AVG(kh.HOCPHI) TrungBinh  
	FROM KhoaHoc kh   JOIN HocVien hv ON kh.MAKHOAHOC=hv.MAKHOAHOC   JOIN ChuyenDe cd ON cd.MACHUYENDE=kh.MACHUYENDE  
	WHERE YEAR(NGAYKHAIGIANG) = @Year  
	GROUP BY TENCHUYENDE
END
GO
---thủ tục thống kê người học
if OBJECT_ID('sp_ThongKeNguoiHoc') is not null
drop proc sp_ThongKeNguoiHoc
go
CREATE PROC sp_ThongKeNguoiHoc 
AS BEGIN  
	SELECT   
		YEAR(NGAYDANGKI) Nam,   
		COUNT(*) SoLuong,   
		MIN(NGAYDANGKI) DauTien,   
		MAX(NGAYDANGKI) CuoiCung  
	FROM NguoiHoc  
	GROUP BY YEAR(NGAYDANGKI) 
END
GO